enum PokemonActionsTypes {
  FETCH_POKEMONS_DATA = 'FETCH_POKEMONS_DATA',
  FETCH_POKEMONS_DATA_SUCCESS = 'FETCH_POKEMONS_DATA_SUCCESS',
  FETCH_POKEMONS_DATA_ERROR = 'FETCH_POKEMONS_DATA_ERROR',

  FETCH_SINGLE_POKEMON_DATA = 'FETCH_SINGLE_POKEMON_DATA',
  FETCH_SINGLE_POKEMON_DATA_SUCCESS = 'FETCH_SINGLE_POKEMON_DATA_SUCCESS',
  FETCH_SINGLE_POKEMON_DATA_ERROR = 'FETCH_SINGLE_POKEMON_DATA_ERROR',
}

export default PokemonActionsTypes
